name: Publish Python Package to PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: |
          pip install --upgrade pip
          pip install uv
          uv add build

      - name: Build the package
        run: uv build

      - name: Publish package to PyPI
        run: uv publish
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
